name: water_drops_processing
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - pip
  - pip:
    - segmentation-models-pytorch==0.3.3
    - timm==0.9.2
    - albumentations==1.3.1 --no-binary qudida,albumentations
    - easydict
    - matplotlib
    - tqdm
    - pyyaml
    - jupyterlab
