name: water_drops_processing
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.0
  - torchvision
  - cudatoolkit=11.8
  - easydict
  - matplotlib
  - tqdm
  - pyyaml
  - pip
  - pip:
    - opencv-python
    - segmentation-models-pytorch==0.3.3
    - timm==0.9.2
    - albumentations==1.3.1 --no-binary qudida,albumentations
