FROM nvcr.io/nvidia/pytorch:23.06-py3

# set bash as current shell
RUN chsh -s /bin/bash
SHELL ["/bin/bash", "-c"]

# fix timezone
ENV TZ=Asia/Novosibirsk
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && \
    apt-get install -y ffmpeg libsm6 libxext6 wget bzip2 ca-certificates \
    libglib2.0-0 libxrender1 git mercurial subversion && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && \
    pip install segmentation-models-pytorch==0.3.3 \
    timm==0.9.2 \
    albumentations==1.3.1 --no-binary qudida,albumentations \
    easydict

ARG MY_NAME
ARG MY_UID
ARG MY_GID

RUN groupadd --gid ${MY_GID} ${MY_NAME} && \
    useradd --create-home --shell /bin/bash --uid ${MY_UID} --gid ${MY_GID} \
    --groups sudo -p $(openssl passwd -1 pass) ${MY_NAME}

USER ${MY_NAME}

ENV PATH "${PATH}:/home/${MY_NAME}/.local/bin"
