#!/bin/bash

MY_NAME=$(whoami)
CONT_NAME=$1
MNT_DIR=$2

docker run --user ${MY_NAME} --name ${CONT_NAME} \
--gpus all -v /dev/shm:/dev/shm -v ${MNT_DIR}:/mnt/ \
-it --rm --ipc=host -p 8888:8888 wdp_pytorch:0.1
